services:
  mssql:
    container_name: sql-server
    image: mcr.microsoft.com/mssql/server:2022-latest
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "p@ssword!1"
      MSSQL_LOGGING: "verbose"
      MSSQL_PID: "Developer"
    ports:
      - 1433:1433
    volumes:
      - ./data:/var/opt/mssql/data
      - ./3:/backup
