// <auto-generated />
using System;
using FileStore.Infrastructure.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace Infrastructure.Migrations
{
    [DbContext(typeof(VideoCatalogDbContext))]
    [Migration("20220618073359_InitialCreate5")]
    partial class InitialCreate5
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.13")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("FileStore.Domain.Models.DbFile", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("Duration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("SeasonId")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeasonId");

                    b.HasIndex("SeriesId");

                    b.ToTable("DbFile");
                });

            modelBuilder.Entity("FileStore.Domain.Models.FileExtendedInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte[]>("Cover")
                        .HasColumnType("varbinary(max)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genres")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("RutrackerId")
                        .HasColumnType("int");

                    b.Property<int>("VideoFileId")
                        .HasColumnType("int");

                    b.Property<int>("Year")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoFileId")
                        .IsUnique();

                    b.ToTable("VideoFileExtendedInfos");
                });

            modelBuilder.Entity("FileStore.Domain.Models.FileUserInfo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("Position")
                        .HasColumnType("float");

                    b.Property<double>("Rating")
                        .HasColumnType("float");

                    b.Property<int>("VideoFileId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("VideoFileId")
                        .IsUnique();

                    b.ToTable("VideoFileUserInfos");
                });

            modelBuilder.Entity("FileStore.Domain.Models.Season", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("IntroDuration")
                        .HasColumnType("time");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SeriesId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("SeriesId");

                    b.ToTable("Seasons");
                });

            modelBuilder.Entity("FileStore.Domain.Models.Series", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<TimeSpan>("IntroDuration")
                        .HasColumnType("time");

                    b.Property<bool>("IsChild")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Origin")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Series");
                });

            modelBuilder.Entity("FileStore.Domain.Models.AudioFile", b =>
                {
                    b.HasBaseType("FileStore.Domain.Models.DbFile");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ToTable("AudioFile");
                });

            modelBuilder.Entity("FileStore.Domain.Models.VideoFile", b =>
                {
                    b.HasBaseType("FileStore.Domain.Models.DbFile");

                    b.Property<bool>("IsDownloading")
                        .HasColumnType("bit");

                    b.Property<int>("Quality")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.ToTable("VideoFile");
                });

            modelBuilder.Entity("FileStore.Domain.Models.DbFile", b =>
                {
                    b.HasOne("FileStore.Domain.Models.Season", "Season")
                        .WithMany("Files")
                        .HasForeignKey("SeasonId")
                        .IsRequired();

                    b.HasOne("FileStore.Domain.Models.Series", "Series")
                        .WithMany("Files")
                        .HasForeignKey("SeriesId")
                        .IsRequired();

                    b.Navigation("Season");

                    b.Navigation("Series");
                });

            modelBuilder.Entity("FileStore.Domain.Models.FileExtendedInfo", b =>
                {
                    b.HasOne("FileStore.Domain.Models.DbFile", "DbFile")
                        .WithOne("VideoFileExtendedInfo")
                        .HasForeignKey("FileStore.Domain.Models.FileExtendedInfo", "VideoFileId")
                        .IsRequired();

                    b.Navigation("DbFile");
                });

            modelBuilder.Entity("FileStore.Domain.Models.FileUserInfo", b =>
                {
                    b.HasOne("FileStore.Domain.Models.DbFile", "DbFile")
                        .WithOne("VideoFileUserInfo")
                        .HasForeignKey("FileStore.Domain.Models.FileUserInfo", "VideoFileId")
                        .IsRequired();

                    b.Navigation("DbFile");
                });

            modelBuilder.Entity("FileStore.Domain.Models.Season", b =>
                {
                    b.HasOne("FileStore.Domain.Models.Series", "Series")
                        .WithMany("Seasons")
                        .HasForeignKey("SeriesId")
                        .IsRequired();

                    b.Navigation("Series");
                });

            modelBuilder.Entity("FileStore.Domain.Models.AudioFile", b =>
                {
                    b.HasOne("FileStore.Domain.Models.DbFile", null)
                        .WithOne()
                        .HasForeignKey("FileStore.Domain.Models.AudioFile", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileStore.Domain.Models.VideoFile", b =>
                {
                    b.HasOne("FileStore.Domain.Models.DbFile", null)
                        .WithOne()
                        .HasForeignKey("FileStore.Domain.Models.VideoFile", "Id")
                        .OnDelete(DeleteBehavior.ClientCascade)
                        .IsRequired();
                });

            modelBuilder.Entity("FileStore.Domain.Models.DbFile", b =>
                {
                    b.Navigation("VideoFileExtendedInfo");

                    b.Navigation("VideoFileUserInfo");
                });

            modelBuilder.Entity("FileStore.Domain.Models.Season", b =>
                {
                    b.Navigation("Files");
                });

            modelBuilder.Entity("FileStore.Domain.Models.Series", b =>
                {
                    b.Navigation("Files");

                    b.Navigation("Seasons");
                });
#pragma warning restore 612, 618
        }
    }
}
